### PR TITLE
Upgrade Labs to 58

### PR DESCRIPTION
**Pull request by brandones**
for https://tickets.pih-emr.org/browse/MEX-301
MEX-301 Glucose question should be asked with "Fasting for glucose test"

### CODE REVIEW

**Comment by brandones** [comment]
@lnball do you want to continue reviewing MDS package changes, or should I just merge them?

**Comment by lnball** [comment]
Could you use Fasting blood glucose (CIEL:160912 or PIH:10536)?  I see that you are asking yes/no and not the test.  However, we would like to model this properly -- order a test (ie. fasting blood glucose) and record the results for that test.  Otherwise we could end up with coded yes/no for every lab test.

If you think this is the way to model this, I would suggest you change the name to something clearer (ie. "patient fasted for test or "patient fasted for blood glucose test").  I think this is the only lab test that a patient  where a patient would fast, but I can check.

**Comment by brandones** [comment]
Oh shoot, I'm getting
```
Caused by: org.openmrs.api.ValidationException: 'Concept #658' failed to validate with reason: Se requiere al menos un nombre que no esté vacío 
        at org.openmrs.validator.ValidateUtil.validate(ValidateUtil.java:82)                                                                    
        at org.openmrs.aop.RequiredDataAdvice.before(RequiredDataAdvice.java:127)                                                               
```

I'll debug that.

**Comment by brandones** [comment]
That modeling isn't how it works in the clinics. In the clinics, the patient arrives for their consult. Their glucose is measured as a matter of routine and they're asked "have you eaten in the last four hours?"

Not sure how you imagine us ending up with a coded yes/no for every lab test.

Perhaps the ideal thing would be a UI element (checkbox or radio) that toggles between whether "PIH:SERUM GLUCOSE" is asked or "CIEL:160912" is asked. That would also be consistent with the design that's been asked for. But that's not something HTMLFormEntry supports right now.

Did you have a particular form design in mind that would support both of those entry options?

**Comment by lnball** [comment]
You could use the fasting question (checkbox) to toggle between the fasting test or (random) glucose test.  I believe this would be simple to implement with javascript -- we do similar things today.

**Comment by brandones** [comment]
Thanks Ellen!

**Pull request merged**
